//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.DokumentooborotKr3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ав пользователи.
    /// </summary>
    // *** Start programmer edit section *** (АвПользователи CustomAttributes)

    // *** End programmer edit section *** (АвПользователи CustomAttributes)
    [AutoAltered()]
    [Caption("Авторизованные пользователи")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АвПользователиE", new string[] {
            "ДатаРегистрации as \'Дата регистрации\'",
            "IDПользователя as \'ID Пользователя\'",
            "Сотрудники as \'ФИО Сотрудника\'",
            "Сотрудники.ФИОСотрудника as \'ФИО Сотрудника\'",
            "Логин as \'Логин\'",
            "Пароль as \'Пароль\'"}, Hidden=new string[] {
            "Сотрудники.ФИОСотрудника"})]
    [AssociatedDetailViewAttribute("АвПользователиE", "ТЧПрава", "ТЧПраваE", true, "", "Права пользователя", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("АвПользователиE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОСотрудника")]
    [View("АвПользователиL", new string[] {
            "ДатаРегистрации as \'Дата регистрации\'",
            "IDПользователя as \'ID Пользователя\'",
            "Сотрудники.ФИОСотрудника as \'ФИО Сотрудника\'",
            "Логин as \'Логин\'",
            "Пароль as \'Пароль\'"})]
    public class АвПользователи : ICSSoft.STORMNET.DataObject
    {
        
        private string fЛогин;
        
        private System.DateTime fДатаРегистрации;
        
        private string fПароль;
        
        private int fIDПользователя;
        
        private IIS.DokumentooborotKr3.Сотрудники fСотрудники;
        
        private IIS.DokumentooborotKr3.DetailArrayOfТЧПрава fТЧПрава;
        
        // *** Start programmer edit section *** (АвПользователи CustomMembers)

        // *** End programmer edit section *** (АвПользователи CustomMembers)

        
        /// <summary>
        /// IDПользователя.
        /// </summary>
        // *** Start programmer edit section *** (АвПользователи.IDПользователя CustomAttributes)

        // *** End programmer edit section *** (АвПользователи.IDПользователя CustomAttributes)
        public virtual int IDПользователя
        {
            get
            {
                // *** Start programmer edit section *** (АвПользователи.IDПользователя Get start)

                // *** End programmer edit section *** (АвПользователи.IDПользователя Get start)
                int result = this.fIDПользователя;
                // *** Start programmer edit section *** (АвПользователи.IDПользователя Get end)

                // *** End programmer edit section *** (АвПользователи.IDПользователя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АвПользователи.IDПользователя Set start)

                // *** End programmer edit section *** (АвПользователи.IDПользователя Set start)
                this.fIDПользователя = value;
                // *** Start programmer edit section *** (АвПользователи.IDПользователя Set end)

                // *** End programmer edit section *** (АвПользователи.IDПользователя Set end)
            }
        }
        
        /// <summary>
        /// ДатаРегистрации.
        /// </summary>
        // *** Start programmer edit section *** (АвПользователи.ДатаРегистрации CustomAttributes)

        // *** End programmer edit section *** (АвПользователи.ДатаРегистрации CustomAttributes)
        public virtual System.DateTime ДатаРегистрации
        {
            get
            {
                // *** Start programmer edit section *** (АвПользователи.ДатаРегистрации Get start)

                // *** End programmer edit section *** (АвПользователи.ДатаРегистрации Get start)
                System.DateTime result = this.fДатаРегистрации;
                // *** Start programmer edit section *** (АвПользователи.ДатаРегистрации Get end)

                // *** End programmer edit section *** (АвПользователи.ДатаРегистрации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АвПользователи.ДатаРегистрации Set start)

                // *** End programmer edit section *** (АвПользователи.ДатаРегистрации Set start)
                this.fДатаРегистрации = value;
                // *** Start programmer edit section *** (АвПользователи.ДатаРегистрации Set end)

                // *** End programmer edit section *** (АвПользователи.ДатаРегистрации Set end)
            }
        }
        
        /// <summary>
        /// Логин.
        /// </summary>
        // *** Start programmer edit section *** (АвПользователи.Логин CustomAttributes)

        // *** End programmer edit section *** (АвПользователи.Логин CustomAttributes)
        [StrLen(255)]
        public virtual string Логин
        {
            get
            {
                // *** Start programmer edit section *** (АвПользователи.Логин Get start)

                // *** End programmer edit section *** (АвПользователи.Логин Get start)
                string result = this.fЛогин;
                // *** Start programmer edit section *** (АвПользователи.Логин Get end)

                // *** End programmer edit section *** (АвПользователи.Логин Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АвПользователи.Логин Set start)

                // *** End programmer edit section *** (АвПользователи.Логин Set start)
                this.fЛогин = value;
                // *** Start programmer edit section *** (АвПользователи.Логин Set end)

                // *** End programmer edit section *** (АвПользователи.Логин Set end)
            }
        }
        
        /// <summary>
        /// Пароль.
        /// </summary>
        // *** Start programmer edit section *** (АвПользователи.Пароль CustomAttributes)

        // *** End programmer edit section *** (АвПользователи.Пароль CustomAttributes)
        [StrLen(255)]
        public virtual string Пароль
        {
            get
            {
                // *** Start programmer edit section *** (АвПользователи.Пароль Get start)

                // *** End programmer edit section *** (АвПользователи.Пароль Get start)
                string result = this.fПароль;
                // *** Start programmer edit section *** (АвПользователи.Пароль Get end)

                // *** End programmer edit section *** (АвПользователи.Пароль Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АвПользователи.Пароль Set start)

                // *** End programmer edit section *** (АвПользователи.Пароль Set start)
                this.fПароль = value;
                // *** Start programmer edit section *** (АвПользователи.Пароль Set end)

                // *** End programmer edit section *** (АвПользователи.Пароль Set end)
            }
        }
        
        /// <summary>
        /// Ав пользователи.
        /// </summary>
        // *** Start programmer edit section *** (АвПользователи.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (АвПользователи.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.DokumentooborotKr3.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (АвПользователи.Сотрудники Get start)

                // *** End programmer edit section *** (АвПользователи.Сотрудники Get start)
                IIS.DokumentooborotKr3.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (АвПользователи.Сотрудники Get end)

                // *** End programmer edit section *** (АвПользователи.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АвПользователи.Сотрудники Set start)

                // *** End programmer edit section *** (АвПользователи.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (АвПользователи.Сотрудники Set end)

                // *** End programmer edit section *** (АвПользователи.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Ав пользователи.
        /// </summary>
        // *** Start programmer edit section *** (АвПользователи.ТЧПрава CustomAttributes)

        // *** End programmer edit section *** (АвПользователи.ТЧПрава CustomAttributes)
        public virtual IIS.DokumentooborotKr3.DetailArrayOfТЧПрава ТЧПрава
        {
            get
            {
                // *** Start programmer edit section *** (АвПользователи.ТЧПрава Get start)

                // *** End programmer edit section *** (АвПользователи.ТЧПрава Get start)
                if ((this.fТЧПрава == null))
                {
                    this.fТЧПрава = new IIS.DokumentooborotKr3.DetailArrayOfТЧПрава(this);
                }
                IIS.DokumentooborotKr3.DetailArrayOfТЧПрава result = this.fТЧПрава;
                // *** Start programmer edit section *** (АвПользователи.ТЧПрава Get end)

                // *** End programmer edit section *** (АвПользователи.ТЧПрава Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АвПользователи.ТЧПрава Set start)

                // *** End programmer edit section *** (АвПользователи.ТЧПрава Set start)
                this.fТЧПрава = value;
                // *** Start programmer edit section *** (АвПользователи.ТЧПрава Set end)

                // *** End programmer edit section *** (АвПользователи.ТЧПрава Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АвПользователиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвПользователиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвПользователиE", typeof(IIS.DokumentooborotKr3.АвПользователи));
                }
            }
            
            /// <summary>
            /// "АвПользователиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвПользователиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвПользователиL", typeof(IIS.DokumentooborotKr3.АвПользователи));
                }
            }
        }
    }
}
