//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.DokumentooborotKr3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "IDСотрудника as \'ID Сотрудника\'",
            "ФИОСотрудника as \'ФИО сотрудника\'",
            "Пол as \'Пол\'",
            "НомерТелефона as \'Номер телефона\'",
            "ДатаПриема as \'Дата приема\'",
            "Должности as \'Должности\'",
            "Должности.Должность as \'Должность\'",
            "Отдел as \'Отдел\'",
            "Отдел.Наименование as \'Отдел\'",
            "Зарплата as \'Зарплата\'"}, Hidden=new string[] {
            "Должности.Должность",
            "Отдел.Наименование"})]
    [MasterViewDefineAttribute("СотрудникиE", "Должности", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Должность")]
    [MasterViewDefineAttribute("СотрудникиE", "Отдел", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("СотрудникиL", new string[] {
            "IDСотрудника as \'ID Сотрудника\'",
            "ФИОСотрудника as \'ФИО Сотрудника\'",
            "Пол as \'Пол\'",
            "НомерТелефона as \'Номер телефона\'",
            "ДатаПриема as \'Дата приема\'",
            "Должности.Должность as \'Должность\'",
            "Отдел.Наименование as \'Отдел\'",
            "Зарплата as \'Зарплата\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private int fIDСотрудника;
        
        private string fФИОСотрудника;
        
        private System.DateTime fДатаПриема;
        
        private double fЗарплата;
        
        private int fНомерТелефона;
        
        private IIS.DokumentooborotKr3.Пол fПол;
        
        private IIS.DokumentooborotKr3.Отдел fОтдел;
        
        private IIS.DokumentooborotKr3.Должности fДолжности;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// IDСотрудника.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.IDСотрудника CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.IDСотрудника CustomAttributes)
        public virtual int IDСотрудника
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.IDСотрудника Get start)

                // *** End programmer edit section *** (Сотрудники.IDСотрудника Get start)
                int result = this.fIDСотрудника;
                // *** Start programmer edit section *** (Сотрудники.IDСотрудника Get end)

                // *** End programmer edit section *** (Сотрудники.IDСотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.IDСотрудника Set start)

                // *** End programmer edit section *** (Сотрудники.IDСотрудника Set start)
                this.fIDСотрудника = value;
                // *** Start programmer edit section *** (Сотрудники.IDСотрудника Set end)

                // *** End programmer edit section *** (Сотрудники.IDСотрудника Set end)
            }
        }
        
        /// <summary>
        /// ДатаПриема.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ДатаПриема CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ДатаПриема CustomAttributes)
        public virtual System.DateTime ДатаПриема
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ДатаПриема Get start)

                // *** End programmer edit section *** (Сотрудники.ДатаПриема Get start)
                System.DateTime result = this.fДатаПриема;
                // *** Start programmer edit section *** (Сотрудники.ДатаПриема Get end)

                // *** End programmer edit section *** (Сотрудники.ДатаПриема Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ДатаПриема Set start)

                // *** End programmer edit section *** (Сотрудники.ДатаПриема Set start)
                this.fДатаПриема = value;
                // *** Start programmer edit section *** (Сотрудники.ДатаПриема Set end)

                // *** End programmer edit section *** (Сотрудники.ДатаПриема Set end)
            }
        }
        
        /// <summary>
        /// Зарплата.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Зарплата CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Зарплата CustomAttributes)
        public virtual double Зарплата
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Зарплата Get start)

                // *** End programmer edit section *** (Сотрудники.Зарплата Get start)
                double result = this.fЗарплата;
                // *** Start programmer edit section *** (Сотрудники.Зарплата Get end)

                // *** End programmer edit section *** (Сотрудники.Зарплата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Зарплата Set start)

                // *** End programmer edit section *** (Сотрудники.Зарплата Set start)
                this.fЗарплата = value;
                // *** Start programmer edit section *** (Сотрудники.Зарплата Set end)

                // *** End programmer edit section *** (Сотрудники.Зарплата Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.НомерТелефона CustomAttributes)
        public virtual int НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.НомерТелефона Get start)

                // *** End programmer edit section *** (Сотрудники.НомерТелефона Get start)
                int result = this.fНомерТелефона;
                // *** Start programmer edit section *** (Сотрудники.НомерТелефона Get end)

                // *** End programmer edit section *** (Сотрудники.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.НомерТелефона Set start)

                // *** End programmer edit section *** (Сотрудники.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (Сотрудники.НомерТелефона Set end)

                // *** End programmer edit section *** (Сотрудники.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// Пол.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Пол CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Пол CustomAttributes)
        public virtual IIS.DokumentooborotKr3.Пол Пол
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Пол Get start)

                // *** End programmer edit section *** (Сотрудники.Пол Get start)
                IIS.DokumentooborotKr3.Пол result = this.fПол;
                // *** Start programmer edit section *** (Сотрудники.Пол Get end)

                // *** End programmer edit section *** (Сотрудники.Пол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Пол Set start)

                // *** End programmer edit section *** (Сотрудники.Пол Set start)
                this.fПол = value;
                // *** Start programmer edit section *** (Сотрудники.Пол Set end)

                // *** End programmer edit section *** (Сотрудники.Пол Set end)
            }
        }
        
        /// <summary>
        /// ФИОСотрудника.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ФИОСотрудника CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОСотрудника
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника Get start)

                // *** End programmer edit section *** (Сотрудники.ФИОСотрудника Get start)
                string result = this.fФИОСотрудника;
                // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника Get end)

                // *** End programmer edit section *** (Сотрудники.ФИОСотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника Set start)

                // *** End programmer edit section *** (Сотрудники.ФИОСотрудника Set start)
                this.fФИОСотрудника = value;
                // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника Set end)

                // *** End programmer edit section *** (Сотрудники.ФИОСотрудника Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Должности CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.DokumentooborotKr3.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Должности Get start)

                // *** End programmer edit section *** (Сотрудники.Должности Get start)
                IIS.DokumentooborotKr3.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (Сотрудники.Должности Get end)

                // *** End programmer edit section *** (Сотрудники.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Должности Set start)

                // *** End programmer edit section *** (Сотрудники.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (Сотрудники.Должности Set end)

                // *** End programmer edit section *** (Сотрудники.Должности Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Отдел CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Отдел CustomAttributes)
        [PropertyStorage(new string[] {
                "Отдел"})]
        [NotNull()]
        public virtual IIS.DokumentooborotKr3.Отдел Отдел
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Отдел Get start)

                // *** End programmer edit section *** (Сотрудники.Отдел Get start)
                IIS.DokumentooborotKr3.Отдел result = this.fОтдел;
                // *** Start programmer edit section *** (Сотрудники.Отдел Get end)

                // *** End programmer edit section *** (Сотрудники.Отдел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Отдел Set start)

                // *** End programmer edit section *** (Сотрудники.Отдел Set start)
                this.fОтдел = value;
                // *** Start programmer edit section *** (Сотрудники.Отдел Set end)

                // *** End programmer edit section *** (Сотрудники.Отдел Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.DokumentooborotKr3.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.DokumentooborotKr3.Сотрудники));
                }
            }
        }
    }
}
