//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.DokumentooborotKr3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч утверж док.
    /// </summary>
    // *** Start programmer edit section *** (ТЧУтвержДок CustomAttributes)

    // *** End programmer edit section *** (ТЧУтвержДок CustomAttributes)
    [AutoAltered()]
    [Caption("Рассмотренные документы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧУтвержДокE", new string[] {
            "РасДок as \'Рассмотренные документы\'",
            "РасДок.Дата as \'Дата\'",
            "РасДок.АвПользователи.Сотрудники.ФИОСотрудника as \'Утверждающее лицо\'",
            "РасДок.АвПользователи.Сотрудники.Отдел.Наименование as \'Утверждающий отдел\'",
            "РасДок.ФормаДокумента.Наименование as \'Наименование документа\'",
            "РасДок.Утверждение as \'Статус решения\'"}, Hidden=new string[] {
            "РасДок.Дата"})]
    [MasterViewDefineAttribute("ТЧУтвержДокE", "РасДок", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Дата")]
    public class ТЧУтвержДок : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.DokumentooborotKr3.РасДок fРасДок;
        
        private IIS.DokumentooborotKr3.ХрДок fХрДок;
        
        // *** Start programmer edit section *** (ТЧУтвержДок CustomMembers)

        // *** End programmer edit section *** (ТЧУтвержДок CustomMembers)

        
        /// <summary>
        /// Т ч утверж док.
        /// </summary>
        // *** Start programmer edit section *** (ТЧУтвержДок.РасДок CustomAttributes)

        // *** End programmer edit section *** (ТЧУтвержДок.РасДок CustomAttributes)
        [PropertyStorage(new string[] {
                "РасДок"})]
        [NotNull()]
        public virtual IIS.DokumentooborotKr3.РасДок РасДок
        {
            get
            {
                // *** Start programmer edit section *** (ТЧУтвержДок.РасДок Get start)

                // *** End programmer edit section *** (ТЧУтвержДок.РасДок Get start)
                IIS.DokumentooborotKr3.РасДок result = this.fРасДок;
                // *** Start programmer edit section *** (ТЧУтвержДок.РасДок Get end)

                // *** End programmer edit section *** (ТЧУтвержДок.РасДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧУтвержДок.РасДок Set start)

                // *** End programmer edit section *** (ТЧУтвержДок.РасДок Set start)
                this.fРасДок = value;
                // *** Start programmer edit section *** (ТЧУтвержДок.РасДок Set end)

                // *** End programmer edit section *** (ТЧУтвержДок.РасДок Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.DokumentooborotKr3.ХрДок.
        /// </summary>
        // *** Start programmer edit section *** (ТЧУтвержДок.ХрДок CustomAttributes)

        // *** End programmer edit section *** (ТЧУтвержДок.ХрДок CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ХрДок"})]
        public virtual IIS.DokumentooborotKr3.ХрДок ХрДок
        {
            get
            {
                // *** Start programmer edit section *** (ТЧУтвержДок.ХрДок Get start)

                // *** End programmer edit section *** (ТЧУтвержДок.ХрДок Get start)
                IIS.DokumentooborotKr3.ХрДок result = this.fХрДок;
                // *** Start programmer edit section *** (ТЧУтвержДок.ХрДок Get end)

                // *** End programmer edit section *** (ТЧУтвержДок.ХрДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧУтвержДок.ХрДок Set start)

                // *** End programmer edit section *** (ТЧУтвержДок.ХрДок Set start)
                this.fХрДок = value;
                // *** Start programmer edit section *** (ТЧУтвержДок.ХрДок Set end)

                // *** End programmer edit section *** (ТЧУтвержДок.ХрДок Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧУтвержДокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧУтвержДокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧУтвержДокE", typeof(IIS.DokumentooborotKr3.ТЧУтвержДок));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧУтвержДок.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧУтвержДок CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧУтвержДок CustomAttributes)
    public class DetailArrayOfТЧУтвержДок : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.DokumentooborotKr3.DetailArrayOfТЧУтвержДок members)

        // *** End programmer edit section *** (IIS.DokumentooborotKr3.DetailArrayOfТЧУтвержДок members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧУтвержДок by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧУтвержДок.
        /// </summary>
        public DetailArrayOfТЧУтвержДок(IIS.DokumentooborotKr3.ХрДок fХрДок) : 
                base(typeof(ТЧУтвержДок), ((ICSSoft.STORMNET.DataObject)(fХрДок)))
        {
        }
        
        public IIS.DokumentooborotKr3.ТЧУтвержДок this[int index]
        {
            get
            {
                return ((IIS.DokumentooborotKr3.ТЧУтвержДок)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.DokumentooborotKr3.ТЧУтвержДок dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
