//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.DokumentooborotKr3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Форма документа.
    /// </summary>
    // *** Start programmer edit section *** (ФормаДокумента CustomAttributes)

    // *** End programmer edit section *** (ФормаДокумента CustomAttributes)
    [AutoAltered()]
    [Caption("Форма документа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормаДокументаE", new string[] {
            "Дата as \'Дата составления\'",
            "АвПользователи as \'ID Пользователя\'",
            "АвПользователи.Сотрудники.ФИОСотрудника as \'Ответственный документа\'",
            "АвПользователи.Сотрудники.Отдел.Наименование as \'Отдел отправителя\'",
            "Наименование as \'Наименование документа\'",
            "Содержание as \'Содержание документа\'",
            "Отдел as \'Отдел получателя\'",
            "Отдел.Наименование as \'Отдел получателя\'"}, Hidden=new string[] {
            "Отдел.Наименование"})]
    [MasterViewDefineAttribute("ФормаДокументаE", "АвПользователи", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "IDПользователя")]
    [MasterViewDefineAttribute("ФормаДокументаE", "Отдел", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ФормаДокументаL", new string[] {
            "Дата as \'Дата составления\'",
            "АвПользователи.Сотрудники.ФИОСотрудника as \'Ответственный документа\'",
            "АвПользователи.Сотрудники.Отдел.Наименование as \'Отдел отправителя\'",
            "Наименование as \'Наименование документа\'",
            "Содержание as \'Содержание документа\'",
            "Отдел.Наименование as \'Отдел получателя\'"})]
    public class ФормаДокумента : ICSSoft.STORMNET.DataObject
    {
        
        private string fСодержание;
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private string fНаименование;
        
        private IIS.DokumentooborotKr3.АвПользователи fАвПользователи;
        
        private IIS.DokumentooborotKr3.Отдел fОтдел;
        
        // *** Start programmer edit section *** (ФормаДокумента CustomMembers)

        // *** End programmer edit section *** (ФормаДокумента CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормаДокумента.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормаДокумента.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормаДокумента.Дата Get start)

                // *** End programmer edit section *** (ФормаДокумента.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормаДокумента.Дата Get end)

                // *** End programmer edit section *** (ФормаДокумента.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаДокумента.Дата Set start)

                // *** End programmer edit section *** (ФормаДокумента.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормаДокумента.Дата Set end)

                // *** End programmer edit section *** (ФормаДокумента.Дата Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ФормаДокумента.Наименование CustomAttributes)

        // *** End programmer edit section *** (ФормаДокумента.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ФормаДокумента.Наименование Get start)

                // *** End programmer edit section *** (ФормаДокумента.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ФормаДокумента.Наименование Get end)

                // *** End programmer edit section *** (ФормаДокумента.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаДокумента.Наименование Set start)

                // *** End programmer edit section *** (ФормаДокумента.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ФормаДокумента.Наименование Set end)

                // *** End programmer edit section *** (ФормаДокумента.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Содержание.
        /// </summary>
        // *** Start programmer edit section *** (ФормаДокумента.Содержание CustomAttributes)

        // *** End programmer edit section *** (ФормаДокумента.Содержание CustomAttributes)
        [StrLen(255)]
        public virtual string Содержание
        {
            get
            {
                // *** Start programmer edit section *** (ФормаДокумента.Содержание Get start)

                // *** End programmer edit section *** (ФормаДокумента.Содержание Get start)
                string result = this.fСодержание;
                // *** Start programmer edit section *** (ФормаДокумента.Содержание Get end)

                // *** End programmer edit section *** (ФормаДокумента.Содержание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаДокумента.Содержание Set start)

                // *** End programmer edit section *** (ФормаДокумента.Содержание Set start)
                this.fСодержание = value;
                // *** Start programmer edit section *** (ФормаДокумента.Содержание Set end)

                // *** End programmer edit section *** (ФормаДокумента.Содержание Set end)
            }
        }
        
        /// <summary>
        /// Форма документа.
        /// </summary>
        // *** Start programmer edit section *** (ФормаДокумента.АвПользователи CustomAttributes)

        // *** End programmer edit section *** (ФормаДокумента.АвПользователи CustomAttributes)
        [PropertyStorage(new string[] {
                "АвПользователи"})]
        [NotNull()]
        public virtual IIS.DokumentooborotKr3.АвПользователи АвПользователи
        {
            get
            {
                // *** Start programmer edit section *** (ФормаДокумента.АвПользователи Get start)

                // *** End programmer edit section *** (ФормаДокумента.АвПользователи Get start)
                IIS.DokumentooborotKr3.АвПользователи result = this.fАвПользователи;
                // *** Start programmer edit section *** (ФормаДокумента.АвПользователи Get end)

                // *** End programmer edit section *** (ФормаДокумента.АвПользователи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаДокумента.АвПользователи Set start)

                // *** End programmer edit section *** (ФормаДокумента.АвПользователи Set start)
                this.fАвПользователи = value;
                // *** Start programmer edit section *** (ФормаДокумента.АвПользователи Set end)

                // *** End programmer edit section *** (ФормаДокумента.АвПользователи Set end)
            }
        }
        
        /// <summary>
        /// Форма документа.
        /// </summary>
        // *** Start programmer edit section *** (ФормаДокумента.Отдел CustomAttributes)

        // *** End programmer edit section *** (ФормаДокумента.Отдел CustomAttributes)
        [PropertyStorage(new string[] {
                "Отдел"})]
        [NotNull()]
        public virtual IIS.DokumentooborotKr3.Отдел Отдел
        {
            get
            {
                // *** Start programmer edit section *** (ФормаДокумента.Отдел Get start)

                // *** End programmer edit section *** (ФормаДокумента.Отдел Get start)
                IIS.DokumentooborotKr3.Отдел result = this.fОтдел;
                // *** Start programmer edit section *** (ФормаДокумента.Отдел Get end)

                // *** End programmer edit section *** (ФормаДокумента.Отдел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаДокумента.Отдел Set start)

                // *** End programmer edit section *** (ФормаДокумента.Отдел Set start)
                this.fОтдел = value;
                // *** Start programmer edit section *** (ФормаДокумента.Отдел Set end)

                // *** End programmer edit section *** (ФормаДокумента.Отдел Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормаДокументаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормаДокументаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормаДокументаE", typeof(IIS.DokumentooborotKr3.ФормаДокумента));
                }
            }
            
            /// <summary>
            /// "ФормаДокументаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормаДокументаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормаДокументаL", typeof(IIS.DokumentooborotKr3.ФормаДокумента));
                }
            }
        }
    }
}
